### ISSUE TITLE
Set setting

### ISSUE THREAD

**Issue by Hamedmmhhdd** [bpqq/photo-video-watermark#2]
Where i have to put my bot token?

**Comment by h1w** [comment]
Hello. In settings.py
`bot = {
    'token': 'set bot token here',
    'admin': 'set admin telegram id here(your id)',
    'allowed_users': ['id 1', 'id 2', 'id 3',],
}`
In the last paragraph, specify the ID who will be allowed to use the bot, including your own, even if you specified it in the admin section. I just don’t remember if I made a separate condition for the admin.

**Comment by Hamedmmhhdd** [comment]
> Hello. In settings.py `bot = { 'token': 'set bot token here', 'admin': 'set admin telegram id here(your id)', 'allowed_users': ['id 1', 'id 2', 'id 3',], }` In the last paragraph, specify the ID who will be allowed to use the bot, including your own, even if you specified it in the admin section. I just don’t remember if I made a separate condition for the admin.

Hi 
Thank for answer
So like this =>    bot = {
    'token': '5220329744:AAG7xcmj06iKo75Qzg-dP_FFKEkHdwbxxxx' , # Bot token
    'admin': '123456789' , # Admin id
    'allowed_users': ['123456789' , '135679533' , '135897555'] # List ids of allowed users
}
¿

**Comment by h1w** [comment]
> > Hello. In settings.py `bot = { 'token': 'set bot token here', 'admin': 'set admin telegram id here(your id)', 'allowed_users': ['id 1', 'id 2', 'id 3',], }` In the last paragraph, specify the ID who will be allowed to use the bot, including your own, even if you specified it in the admin section. I just don’t remember if I made a separate condition for the admin.
> 
> Hi Thank for answer So like this => bot = { 'token': '5220329744:AAG7xcmj06iKo75Qzg-dP_FFKEkHdwbxxxx' , # Bot token 'admin': '123456789' , # Admin id 'allowed_users': ['123456789' , '135679533' , '135897555'] # List ids of allowed users } ¿

Yes that's right. But you published the key of the bot, change it please. Good luck =)

**Comment by h1w** [comment]
If it doesn't work, remove the quotes for IDs(admin, allowed_users)

**Comment by Hamedmmhhdd** [comment]
> > > Hello. In settings.py `bot = { 'token': 'set bot token here', 'admin': 'set admin telegram id here(your id)', 'allowed_users': ['id 1', 'id 2', 'id 3',], }` In the last paragraph, specify the ID who will be allowed to use the bot, including your own, even if you specified it in the admin section. I just don’t remember if I made a separate condition for the admin.
> > 
> > 
> > Hi Thank for answer So like this => bot = { 'token': '5220329744:AAG7xcmj06iKo75Qzg-dP_FFKEkHdwbxxxx' , # Bot token 'admin': '123456789' , # Admin id 'allowed_users': ['123456789' , '135679533' , '135897555'] # List ids of allowed users } ¿
> 
> Yes that's right. But you published the key of the bot, change it please. Good luck =)

Thank you
I put x four letters of the bot token :))

**Comment by Hamedmmhhdd** [comment]
> If it doesn't work, remove the quotes for IDs(admin, allowed_users)

Okay thank 🙏
